version: '3.8'

services:
  user-statistics-db:
    image: postgres:16.3
    env_file:
      - user-statistics-db.env
    container_name: user-statistics-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes: 
      - postgres-db:/data/postgres
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge

volumes:
  postgres-db:
    driver: local
